version: 2
jobs:
  build:
    working_directory: /go/src/github.com/pankona/gomo-simra
    docker:
      - image: pankona/gomo-simra
    environment:
      - GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: go get
          command: go get
      - run:
          name: run golangci-lint
          command: make lint
      - run:
          name: make example for linux
          command: |
            make -C examples
            make -C examples BUILD_TAGS=release
      - run:
          name: make example for mobile
          environment:
          command: |
            go mod vendor
            export GO111MODULE=off
            make mobile -C examples
            make mobile -C examples BUILD_TAGS=release
      - run:
          name: run test
          command: cd simra && go test ./...

workflows:
  version: 2
  build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 5 * * *" # run at 05:00
