defaults: &defaults
  working_directory: /go/src/github.com/pankona/gomo-simra
  docker:
    - image: pankona/gomo-simra

version: 2
jobs:
  lint:
     <<: *defaults
     steps:
      - checkout
      - run:
          name: go lint for simra examples
          command: cd examples && golint ./...
      - run:
          name: go lint for simra lib
          command: cd simra && golint ./...
      - run:
          name: run gometalinter
          command: make gometalinter

  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: make example for linux
          command: |
            make -C examples
            make -C examples BUILD_TAGS=release
      - run:
          name: make example for mobile
          command: |
            make mobile -C examples
            make mobile -C examples BUILD_TAGS=release

  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: go test
          command: cd simra && go test ./...

workflows:
  version: 2
  build:
    jobs:
      - lint
      - build
      - test
