version: 2
jobs:
  build:
    working_directory: /go/src/github.com/pankona/gomo-simra
    docker:
      - image: pankona/gomo-simra
    steps:
      - checkout
      - run:
          name: run test
          command: make test
      - run:
          name: run golangci-lint
          command: make lint
      - run:
          name: make example for linux
          command: |
            make -C examples
            make -C examples BUILD_TAGS=release
      - run:
          name: make example for mobile
          command: |
            make mobile -C examples
            make mobile -C examples BUILD_TAGS=release

workflows:
  version: 2
  per-commit:
    jobs:
      - build
  daily-build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 20 * * *" # run at 05:00 JST
          filters:
            branches:
              only:
                - master
