version: 2
jobs:
  prepare:
    working_directory: /home/circleci # $HOME
    docker:
      - image: circleci/golang:1.10.3
    environment:
      - NDK: "android-ndk-r15c"
    steps:
      - run:
          name: configure environment variables
          command: |
            echo 'export NDK_ROOT=$HOME/$NDK' >> $BASH_ENV
            echo 'export GOPATH=$HOME/go' >> $BASH_ENV
            echo 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV
      - restore_cache:
          keys:
            - ndk
      - run:
          name: install dependencies by apt-get
          command: sudo apt-get update; sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev libx11-dev libasound2-dev
      - run:
          name: download ndk
          command: |
            if [ ! -e $NDK_ROOT ]; then
              wget https://dl.google.com/android/repository/$NDK-linux-x86_64.zip
            fi
      - run:
          name: unzip ndk
          command: |
            if [ ! -e $NDK_ROOT ]; then
              unzip -q $NDK-linux-x86_64.zip
            fi
      - save_cache:
          key: ndk
          paths:
            - $NDK_ROOT
      - run:
          name: download dependencies by go get
          command: |
            go get -u golang.org/x/mobile/cmd/gomobile
            go get -u github.com/golang/freetype/truetype
            go get -u github.com/boltdb/bolt
            go get -u github.com/hajimehoshi/oto
            go get -u github.com/hajimehoshi/go-mp3
            go get -u github.com/golang/lint/golint
            go get -u gopkg.in/alecthomas/gometalinter.v2
      - run:
          name: install gometalinter
          command: gometalinter.v2 --install --update
      - run:
          name: gomobile init
          command: |
            echo $NDK_ROOT
            ls $NDK_ROOT
            gomobile init --ndk $NDK_ROOT
      - persist_to_workspace:
          root: .
          paths:
            - $NDK
            - go

  build:
    working_directory: /go/src/github.com/pankona/gomo-simra
    docker:
      - image: circleci/golang:1.10.3
    steps:
      - checkout
      - run:
          name: configure environment variables
          command: |
            echo 'export GOPATH=$HOME/go' >> $BASH_ENV
            echo 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV
      - run:
          name: make example for linux
          command: |
            make -C examples
            make -C examples BUILD_TAGS=release
      - run:
          name: make example for mobile
          command: |
            make mobile -C examples
            make mobile -C examples BUILD_TAGS=release

  lint:
    working_directory: /go/src/github.com/pankona/gomo-simra
    docker:
      - image: circleci/golang:1.10.3
    steps:
      - checkout
      - run:
          name: configure environment variables
          command: |
            echo 'export GOPATH=$HOME/go' >> $BASH_ENV
            echo 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV
      - run:
          name: go lint for simra examples
          command: cd examples && golint ./...
      - run:
          name: go lint for simra lib
          command: cd simra && golint ./...
      - run:
          name: run gometalinter
          command: make gometalinter

  test:
    working_directory: /go/src/github.com/pankona/gomo-simra
    docker:
      - image: circleci/golang:1.10.3
    steps:
      - checkout
      - run:
          name: go test
          command: |
            cd simra && go test ./...

workflows:
  version: 2
  build:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - test:
          requires:
            - prepare
